
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 6;
  public static final int GEQ = 11;
  public static final int LT = 10;
  public static final int ELSE = 18;
  public static final int PLUS = 4;
  public static final int RBRACE = 25;
  public static final int RPAREN = 23;
  public static final int INT = 2;
  public static final int SEMI = 21;
  public static final int WHILE = 16;
  public static final int RETURN = 19;
  public static final int IF = 17;
  public static final int LBRACE = 24;
  public static final int LPAREN = 22;
  public static final int GT = 12;
  public static final int ID = 26;
  public static final int COMMA = 20;
  public static final int NUMBER = 27;
  public static final int EOF = 0;
  public static final int DIVIDE = 7;
  public static final int MINUS = 5;
  public static final int error = 1;
  public static final int ASSIGN = 15;
  public static final int EQ = 13;
  public static final int LEQ = 9;
  public static final int NEQ = 14;
  public static final int VOID = 3;
  public static final int MODULUS = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "VOID",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MODULUS",
  "LEQ",
  "LT",
  "GEQ",
  "GT",
  "EQ",
  "NEQ",
  "ASSIGN",
  "WHILE",
  "IF",
  "ELSE",
  "RETURN",
  "COMMA",
  "SEMI",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "ID",
  "NUMBER"
  };
}

